[package]
name = "inference"
version = "0.1.0"
edition = "2023_10"

[dependencies]
node_fc1_weight = { path = "../initializers/node_fc1_weight"} 
node_fc1_bias = { path = "../initializers/node_fc1_bias"} 
node_fc2_weight = { path = "../initializers/node_fc2_weight"} 
node_fc2_bias = { path = "../initializers/node_fc2_bias"} 
node_fc3_weight = { path = "../initializers/node_fc3_weight"} 
node_fc3_bias = { path = "../initializers/node_fc3_bias"} 
node_fc4_weight = { path = "../initializers/node_fc4_weight"} 
node_fc4_bias = { path = "../initializers/node_fc4_bias"} 
node_fc5_weight = { path = "../initializers/node_fc5_weight"} 
node_fc5_bias = { path = "../initializers/node_fc5_bias"} 
orion = { git = "https://github.com/gizatechxyz/orion.git", rev = "57871a4" } 


[cairo]
enable-gas = false